name: Merge CI

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    name: On Merge-Push CI
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Get version
        if: steps.check.outputs.changed == 'true'
        run: echo "client_version=$(node -pe "require('./package.json').version")" >> $GITHUB_ENV

      - name: Tag and push
        if: steps.check.outputs.changed == 'true'
        run: |
          git tag v${{ env.client_version }}
          git push origin v${{ env.client_version }}
