name: Merge CI

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    name: On Merge-Push CI
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Tag and push
        run: |
          git tag v${{ env.client_version }}
          git push origin v${{ env.client_version }}
