name: Node.js CI

on:
  pull_request:
    branches: [ master ]
    types: [closed]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-22.04
    name: Build and test code
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2

      - name : Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Build mod
        run: npm run build-mod

      - name: Tests
        run: npm run test-translation && npm run test-unit && npm run test-integration

  publish-npm:
    needs: build
    name: Publish API Client to NPM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name : Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: https://registry.npmjs.org/

      - name: Check version changes
        id: check
        uses: EndBug/version-check@v1
        with:
          diff-search: true
          file-name: package.json
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Install dependencies
        if: steps.check.outputs.changed == 'true'
        run: npm ci

      - name: Build mod
        if: steps.check.outputs.changed == 'true'
        run: npm run build-mod

      - name: Build Web Lib
        if: steps.check.outputs.changed == 'true'
        run: npm run build

      - name: Publish to NPM
        if: steps.check.outputs.changed == 'true'
        run: cd ./dist && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-release:
    needs: build
    name: Upload Release Asset
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name : Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1
        with:
          diff-search: true
          file-name: package.json
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        if: steps.check.outputs.changed == 'true'
        run: npm ci

      - name: Build Web Lib
        if: steps.check.outputs.changed == 'true'
        run: npm run build

      - name: Build project # This would actually build your project, using zip for an example artifact
        if: steps.check.outputs.changed == 'true'
        run: |
          zip --junk-paths fsi_server_api_client dist/*

      - name: Get version
        if: steps.check.outputs.changed == 'true'
        run: echo "client_version=$(node -pe "require('./package.json').version")" >> $GITHUB_ENV

      - name: Create Release
        if: steps.check.outputs.changed == 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.client_version }}
          release_name: Release v${{ env.client_version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: steps.check.outputs.changed == 'true'
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./fsi_server_api_client.zip
          asset_name: fsi_server_api_client.zip
          asset_content_type: application/zip
